"""Pydantic request/response models for the CortexAI API (docs/PROJECT_PLAN.md P5).

Every response that carries a prediction includes the responsible-AI fields
(`disclaimer`, `deferred_to_human`) directly in the schema, not as an
optional afterthought -- so no endpoint can accidentally ship a prediction
without the decision-support framing attached.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

from src.data.schemas import TABULAR_FEATURE_COLUMNS

DECISION_SUPPORT_DISCLAIMER = (
    "This is decision-support information generated by an automated system, not a "
    "medical diagnosis. Please consult a qualified healthcare professional."
)


class TabularFeaturesIn(BaseModel):
    """The 18 named features from docs/1.docx. All required -- tabular is the
    only modality guaranteed to carry real ground truth, so unlike face/speech
    it is not optional in an assessment request.
    """

    Sleep_Quality: float
    Social_Engagement: float
    Daily_App_Usage_Min: float
    Typing_Speed_WPM: float
    Session_Frequency: float
    Idle_Time_Min: float
    Facial_Emotion_Variance: float
    Eye_Blink_Rate: float
    Smile_Intensity: float
    Head_Motion_Index: float
    MFCC_Mean: float
    MFCC_Variance: float
    Pitch_Mean: float
    Speech_Rate: float
    Heart_Rate_BPM: float
    HRV_Index: float
    Skin_Temperature: float
    GSR_Level: float

    def to_ordered_list(self) -> list[float]:
        data = self.model_dump()
        return [data[col] for col in TABULAR_FEATURE_COLUMNS]


class AssessmentRequest(BaseModel):
    """A new assessment. `face_image_base64` / `speech_audio_base64` are
    optional -- CortexAI is designed to degrade gracefully with a missing
    modality (modality dropout, src/models/fusion.py), matching real clinics
    that rarely have a perfect webcam+mic+wearable trio available.
    """

    tabular_features: TabularFeaturesIn
    face_image_base64: str | None = Field(default=None, description="PNG/JPEG, base64-encoded, 48x48 grayscale preferred")
    speech_audio_base64: str | None = Field(default=None, description="WAV, base64-encoded, 16kHz preferred")
    patient_id: str | None = Field(default=None, description="Patient identifier")
    demographic: str | None = Field(default=None, description="Demographic segment (Adults, Seniors, Adolescents)")


class ModalityWeights(BaseModel):
    face: float
    speech: float
    tabular: float


class ScoreBreakdown(BaseModel):
    Depression_Score: float
    Anxiety_Score: float
    Stress_Score: float


class UncertaintyInfo(BaseModel):
    defer: bool
    reason: str | None
    mc_dropout_confidence: float


class PredictionResponse(BaseModel):
    session_id: str
    predicted_class: str
    confidence: float
    class_probs: list[float] = Field(
        default_factory=list,
        description="MC-dropout mean probability per class, index-aligned to "
        "StressLevel (0=Healthy, 1=Mild, 2=Moderate, 3=Severe).",
    )
    scores: ScoreBreakdown
    modality_weights: ModalityWeights
    face_emotion_probs: dict[str, float] = Field(
        default_factory=dict, description="7-way FER emotion distribution; empty when no face was supplied."
    )
    speech_emotion_probs: dict[str, float] = Field(
        default_factory=dict, description="8-way RAVDESS emotion distribution; empty when no clip was supplied."
    )
    uncertainty: UncertaintyInfo
    deferred_to_human: bool
    is_demo_untrained_model: bool = Field(
        description="True when any module on the served path has no trained checkpoint loaded. "
        "The numbers above are structurally valid but not a real signal in that case."
    )
    disclaimer: str = DECISION_SUPPORT_DISCLAIMER


class GradCAMPayload(BaseModel):
    """Face Grad-CAM, pre-rendered server-side so the client just displays it."""

    overlay_png_base64: str = Field(description="PNG (base64) of the heatmap blended over the submitted face")
    heatmap: list[list[float]] = Field(description="Raw 48x48 CAM in [0,1], for clients that render their own")
    target_layer: str
    predicted_emotion: str


class AudioIGPayload(BaseModel):
    """Integrated-Gradients attribution over the waveform, pooled to frames."""

    frame_importance: list[float] = Field(description="Per-frame |attribution|, peak-normalised to [0,1]")
    frame_ms: float
    predicted_emotion: str


class ExplanationResponse(BaseModel):
    session_id: str
    top_shap_features: list[dict]
    signed_shap: list[dict] = Field(
        default_factory=list,
        description="Signed SHAP for this row: positive raises predicted severity, negative lowers it.",
    )
    modality_weights: ModalityWeights
    masked_distress_index: dict | None
    gradcam: GradCAMPayload | None = None
    audio_integrated_gradients: AudioIGPayload | None = None
    is_demo_untrained_model: bool = False
    disclaimer: str = DECISION_SUPPORT_DISCLAIMER


class CounterfactualResponse(BaseModel):
    session_id: str
    counterfactual: dict | None
    narrative: str | None
    disclaimer: str = DECISION_SUPPORT_DISCLAIMER


class ReportResponse(BaseModel):
    session_id: str
    narrative: str
    citations: list[str]
    cached: bool
    generator: str = Field(
        default="template",
        description="Which generator wrote this: 'ollama:llama3.1', 'anthropic:<model>', or 'template'.",
    )
    fallback_reason: str | None = Field(
        default=None,
        description="Set when the local LLM was unavailable and a templated summary was served "
        "instead. Shown to the user so a template is never mistaken for a model-written narrative.",
    )
    from_store: bool = Field(
        default=False,
        description="True when this narrative was read back from the database rather than "
        "generated on this request. Orthogonal to `cached`: a stored llama3.1 narrative is "
        "from_store=True but cached=False, because it is still model-written.",
    )
    disclaimer: str = DECISION_SUPPORT_DISCLAIMER


class FollowUpRequest(BaseModel):
    session_id: str
    question: str


class FollowUpResponse(BaseModel):
    session_id: str
    answer: str
    citations: list[str]
    cached: bool
    generator: str = "template"
    fallback_reason: str | None = None
    disclaimer: str = DECISION_SUPPORT_DISCLAIMER


class ReasoningStatus(BaseModel):
    """State of the local Ollama reasoning stack, surfaced on /health so the
    UI can warn before an assessment rather than after the report degrades.
    """

    ollama_reachable: bool
    base_url: str
    llm_model: str
    llm_available: bool
    embedding_model: str
    embedding_available: bool
    retrieval_backend: str | None = None
    vector_index: str | None = None
    detail: str | None = Field(
        default=None, description="Actionable message when something is missing (e.g. `ollama pull ...`)."
    )
