"""Pydantic request/response models for the CortexAI API (docs/PROJECT_PLAN.md P5).

Every response that carries a prediction includes the responsible-AI fields
(`disclaimer`, `deferred_to_human`) directly in the schema, not as an
optional afterthought -- so no endpoint can accidentally ship a prediction
without the decision-support framing attached.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

from src.data.schemas import TABULAR_FEATURE_COLUMNS

DECISION_SUPPORT_DISCLAIMER = (
    "This is decision-support information generated by an automated system, not a "
    "medical diagnosis. Please consult a qualified healthcare professional."
)


class TabularFeaturesIn(BaseModel):
    """The 18 named features from docs/1.docx. All required -- tabular is the
    only modality guaranteed to carry real ground truth, so unlike face/speech
    it is not optional in an assessment request.
    """

    Sleep_Quality: float
    Social_Engagement: float
    Daily_App_Usage_Min: float
    Typing_Speed_WPM: float
    Session_Frequency: float
    Idle_Time_Min: float
    Facial_Emotion_Variance: float
    Eye_Blink_Rate: float
    Smile_Intensity: float
    Head_Motion_Index: float
    MFCC_Mean: float
    MFCC_Variance: float
    Pitch_Mean: float
    Speech_Rate: float
    Heart_Rate_BPM: float
    HRV_Index: float
    Skin_Temperature: float
    GSR_Level: float

    def to_ordered_list(self) -> list[float]:
        data = self.model_dump()
        return [data[col] for col in TABULAR_FEATURE_COLUMNS]


class AssessmentRequest(BaseModel):
    """A new assessment. `face_image_base64` / `speech_audio_base64` are
    optional -- CortexAI is designed to degrade gracefully with a missing
    modality (modality dropout, src/models/fusion.py), matching real clinics
    that rarely have a perfect webcam+mic+wearable trio available.
    """

    tabular_features: TabularFeaturesIn
    face_image_base64: str | None = Field(default=None, description="PNG/JPEG, base64-encoded, 48x48 grayscale preferred")
    speech_audio_base64: str | None = Field(default=None, description="WAV, base64-encoded, 16kHz preferred")


class ModalityWeights(BaseModel):
    face: float
    speech: float
    tabular: float


class ScoreBreakdown(BaseModel):
    Depression_Score: float
    Anxiety_Score: float
    Stress_Score: float


class UncertaintyInfo(BaseModel):
    defer: bool
    reason: str | None
    mc_dropout_confidence: float


class PredictionResponse(BaseModel):
    session_id: str
    predicted_class: str
    confidence: float
    scores: ScoreBreakdown
    modality_weights: ModalityWeights
    uncertainty: UncertaintyInfo
    deferred_to_human: bool
    is_demo_untrained_model: bool = Field(
        description="True when the underlying encoders have no trained checkpoint loaded "
        "(this sandbox has none -- see PROJECT_PLAN.md). The numbers above are structurally "
        "valid but not a real clinical signal in that case."
    )
    disclaimer: str = DECISION_SUPPORT_DISCLAIMER


class ExplanationResponse(BaseModel):
    session_id: str
    top_shap_features: list[dict]
    modality_weights: ModalityWeights
    masked_distress_index: dict | None
    disclaimer: str = DECISION_SUPPORT_DISCLAIMER


class CounterfactualResponse(BaseModel):
    session_id: str
    counterfactual: dict | None
    narrative: str | None
    disclaimer: str = DECISION_SUPPORT_DISCLAIMER


class ReportResponse(BaseModel):
    session_id: str
    narrative: str
    citations: list[str]
    cached: bool
    disclaimer: str = DECISION_SUPPORT_DISCLAIMER


class FollowUpRequest(BaseModel):
    session_id: str
    question: str


class FollowUpResponse(BaseModel):
    session_id: str
    answer: str
    citations: list[str]
    cached: bool
    disclaimer: str = DECISION_SUPPORT_DISCLAIMER
